-- This migration was accidentally committed after
-- 20260322193000_add_file_assets had already introduced FileAsset.
-- Keep the migration directory so Prisma histories stay aligned, but
-- make the SQL a no-op so later migrations can continue to apply.
